### ISSUE TITLE
srtp: unsupported parameter

### ISSUE THREAD

**Issue by michael-borisov** [membraneframework/ex_libsrtp#8]
Hello guys! Thanks for your work!
I tried to run `membrane_demo/blob/master/webrtc/videoroom/` demo, but get this error message: 

```
04:22:03.947 [error] GenServer #PID<0.566.0> terminating
** (stop) "srtp: unsupported parameter"
    (ex_libsrtp 0.1.0) ExLibSRTP.Native.Nif.unifex_unprotect(#Reference<0.1464776169.757465090.48325>, :rtp, <<21, 254, 253, 0, 1, 0, 0, 0, 0, 0, 1, 0, 26, 0, 1, 0, 0, 0, 0, 0, 1, 14, 107, 152, 229, 238, 127, 231, 163, 226, 171, 184, 102, 253, 83, 61, 76, 244, 176>>, false)
    (membrane_rtp_plugin 0.5.0) lib/membrane/srtp/decryptor.ex:91: Membrane.SRTP.Decryptor.handle_process/4
    (membrane_core 0.6.1) lib/membrane/core/callback_handler.ex:128: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.6.1) lib/membrane/core/callback_handler.ex:97: anonymous fn/7 in Membrane.Core.CallbackHandler.exec_and_handle_splitted_callback/6
    (bunch 1.3.0) lib/bunch/enum.ex:159: anonymous fn/3 in Bunch.Enum.try_reduce_while/3
    (elixir 1.11.2) lib/enum.ex:3764: Enumerable.List.reduce/3
    (elixir 1.11.2) lib/enum.ex:2231: Enum.reduce_while/3
    (membrane_core 0.6.1) lib/membrane/core/element/action_handler.ex:24: Membrane.Core.Element.ActionHandler.handle_action/4
Last message: {Membrane.Core.Message, :buffer, [%Membrane.Buffer{metadata: %{}, payload: <<21, 254, 253, 0, 1, 0, 0, 0, 0, 0, 1, 0, 26, 0, 1, 0, 0, 0, 0, 0, 1, 14, 107, 152, 229, 238, 127, 231, 163, 226, 171, 184, 102, 253, 83, 61, 76, 244, 176>>}], [for_pad: :input]}
```

OS X Catalina 10.15.7
Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.11.2 (compiled with Erlang/OTP 23)

srtp package was reinstalled with brew

mix deps:
```
* bimap 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (bimap) 2cb7959a
  ok
* bunch 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (bunch) 9ad233a2
  ok
* bunch_native 0.3.0 (Hex package) (mix)
  locked at 0.3.0 (bunch_native) 8a3b4b4b
  ok
* bundlex 0.4.1 (Hex package) (mix)
  locked at 0.4.1 (bundlex) 8779fe38
  ok
* coerce 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (coerce) b44a6917
  ok
* cowboy 2.8.0 (Hex package) (rebar3)
  locked at 2.8.0 (cowboy) 4643e4fb
  ok
* cowboy_telemetry 0.3.1 (Hex package) (rebar3)
  locked at 0.3.1 (cowboy_telemetry) 3a6efd33
  ok
* cowlib 2.9.1 (Hex package) (rebar3)
  locked at 2.9.1 (cowlib) e4175dc2
  ok
* ex_dtls 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (ex_dtls) 1fc5d5b8
  ok
* ex_libnice 0.1.2 (https://github.com/membraneframework/ex_libnice.git - origin/master) (mix)
  locked at 2a2e501 (branch: master)
  ok
* ex_libsrtp 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (ex_libsrtp) 0495442f
  ok
* ex_sdp 0.3.0 (https://github.com/membraneframework/ex_sdp.git) (mix)
  locked at 94a42d4
  ok
* heap 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (heap) ba9ea2fe
  ok
* membrane_caps_audio_raw 0.3.0 (Hex package) (mix)
  locked at 0.3.0 (membrane_caps_audio_raw) 2a7eb10b
  ok
* membrane_caps_video_h264 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (membrane_caps_video_h264) 36e447b8
  ok
* membrane_caps_video_raw 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (membrane_caps_video_raw) 3f60d651
  ok
* membrane_common_c 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (membrane_common_c) 58716110
  ok
* membrane_core 0.6.1 (https://github.com/membraneframework/membrane_core.git - origin/develop) (mix)
  locked at 5dec691 (branch: develop)
  ok
* membrane_dtls_plugin 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (membrane_dtls_plugin) 5b0ee212
  ok
* membrane_element_fake 0.4.0 (Hex package) (mix)
  locked at 0.4.0 (membrane_element_fake) 92dbac10
  ok
* membrane_element_tee 0.4.1 (Hex package) (mix)
  locked at 0.4.1 (membrane_element_tee) 5467f970
  ok
* membrane_funnel_plugin 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (membrane_funnel_plugin) e3ee4def
  ok
* membrane_h264_ffmpeg_plugin 0.7.0 (https://github.com/membraneframework/membrane_h264_ffmpeg_plugin.git - origin/wait-for-keyframe) (mix)
  locked at 4fb1d36 (branch: wait-for-keyframe)
  ok
* membrane_ice_plugin 0.3.1 (https://github.com/membraneframework/membrane_ice_plugin.git) (mix)
  locked at 5175473
  ok
* membrane_opus_format 0.3.0 (Hex package) (mix)
  locked at 0.3.0 (membrane_opus_format) 8fc89c97
  ok
* membrane_opus_plugin 0.2.1 (Hex package) (mix)
  locked at 0.2.1 (membrane_opus_plugin) 32144eab
  ok
* membrane_remote_stream_format 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (membrane_remote_stream_format) a6f01aa5
  ok
* membrane_rtp_format 0.3.1 (Hex package) (mix)
  locked at 0.3.1 (membrane_rtp_format) d225f453
  ok
* membrane_rtp_h264_plugin 0.4.0 (https://github.com/membraneframework/membrane_rtp_h264_plugin.git) (mix)
  locked at add261f
  ok
* membrane_rtp_opus_plugin 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (membrane_rtp_opus_plugin) f716633a
  ok
* membrane_rtp_plugin 0.5.0 (https://github.com/membraneframework/membrane_rtp_plugin.git - origin/inband-rtcp) (mix)
  locked at 61c8e86 (branch: inband-rtcp)
  ok
* membrane_webrtc_plugin 0.1.0 (https://github.com/membraneframework/membrane_webrtc_plugin.git - origin/endpoint) (mix)
  locked at a1d327a (branch: endpoint)
  ok
* mime 1.5.0 (Hex package) (mix)
  locked at 1.5.0 (mime) 55a94c0f
  ok
* numbers 5.2.4 (Hex package) (mix)
  locked at 5.2.4 (numbers) eeccf5c6
  ok
* plug 1.11.0 (Hex package) (mix)
  locked at 1.11.0 (plug) 2d9c633f
  ok
* plug_cowboy 2.4.1 (Hex package) (mix)
  locked at 2.4.1 (plug_cowboy) d72113b6
  ok
* plug_crypto 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (plug_crypto) 6961c0e1
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) fec8660e
  ok
* qex 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (qex) 4ad6f642
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 451d8527
  ok
* ratio 2.4.2 (Hex package) (mix)
  locked at 2.4.2 (ratio) 441ef6f7
  ok
* secure_random 0.5.1 (Hex package) (mix)
  locked at 0.5.1 (secure_random) 1b9754f1
  ok
* shmex 0.3.0 (Hex package) (mix)
  locked at 0.3.0 (shmex) 05b2cc45
  ok
* telemetry 0.4.2 (Hex package) (rebar3)
  locked at 0.4.2 (telemetry) 2d1419bd
  ok
* unifex 0.3.3 (Hex package) (mix)
  locked at 0.3.3 (unifex) 45278058
  ok
* uuid 1.1.8 (Hex package) (mix)
  locked at 1.1.8 (uuid) c790593b
  ok
  ```

**Comment by mickel8** [comment]
Hi @michael-borisov,
this packet is probably DTLS alert which shouldn't be passed to libsrtp. It will be fixed in membraneframework/ex_dtls#8. We have been getting this error only while exiting the browser so far.

**Comment by michael-borisov** [comment]
I getting this message when clicking the Stop button in demo

**Comment by mickel8** [comment]
Hi @michael-borisov, we have merged a new version of videoroom demo. DTLS alerts should now be supported correctly and you shouldn't get any errors while closing browser's tabs.  At this moment there is no `stop` button in demo. 

Link to new version: https://github.com/membraneframework/membrane_demo/tree/master/webrtc/videoroom

Feel free to reopen if any problems still occur.

**Comment by michael-borisov** [comment]
@mickel8 thank you very much! Great work!
